# Generated by Django 4.2.14 on 2024-10-06 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("module_menu", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menunamesmode",
            options={"verbose_name": "Заголовок меню", "verbose_name_plural": "Меню"},
        ),
        migrations.RenameField(
            model_name="menunamesmode",
            old_name="pages",
            new_name="pages_id",
        ),
    ]
