# Generated by Django 4.2.14 on 2024-10-05 23:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_menu", "0002_alter_linksmode_texts_alter_sublinksmode_texts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linksmode",
            name="links",
            field=models.CharField(
                help_text="ваш/маршрут/на/внутреннюю/страницу/сайта/",
                max_length=100,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        limit_value=100, message="Максимальная длина 100 символов"
                    ),
                    django.core.validators.RegexValidator(
                        message="Неверный формат ссылки.",
                        regex="^(?!.*  )[a-zA-Zа-яА-ЯёЁ][\\w \\-_\\dа-яА-ЯёЁ]{0,98}[a-zA-Zа-яА-ЯёЁ0-9\\/]$",
                    ),
                ],
                verbose_name="Маршрут",
            ),
        ),
        migrations.AlterField(
            model_name="linksmode",
            name="texts",
            field=models.CharField(
                blank=True,
                help_text="Заголовок пункта меню (ссылки)",
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        limit_value=50, message="Максимальная длина 30 символов"
                    ),
                    django.core.validators.RegexValidator(
                        message="\n                    Название не должно иметь двух пробелов подряд,\n                    символов не принадлежащих к алфавиту и(или) цифрам.\n                    Начинается из любой буквы. Заканчивается из любой буквы\n                    и(или) цифры.\n                    Допускается дефис и(или) нижнее подчёркивание\n                    ",
                        regex="^(?!.*  )[a-zA-Z][\\w \\-_\\d]{1,28}[a-zA-Z0-9]$[^\\S\\W \\\\]?",
                    ),
                ],
                verbose_name="Текст ссылки",
            ),
        ),
        migrations.AlterField(
            model_name="sublinksmode",
            name="texts",
            field=models.CharField(
                blank=True,
                help_text="Заголовок пункта меню (ссылки)",
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        limit_value=50, message="Максимальная длина 30 символов"
                    ),
                    django.core.validators.RegexValidator(
                        message="\n                    Название не должно иметь двух пробелов подряд,\n                    символов не принадлежащих к алфавиту и(или) цифрам.\n                    Начинается из любой буквы. Заканчивается из любой буквы\n                    и(или) цифры.\n                    Допускается дефис и(или) нижнее подчёркивание\n                    ",
                        regex="^(?!.*  )[a-zA-Z][\\w \\-_\\d]{1,28}[a-zA-Z0-9]$[^\\S\\W \\\\]?",
                    ),
                ],
                verbose_name="Текст ссылки",
            ),
        ),
    ]
