# Generated by Django 4.2.14 on 2024-10-05 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("module_menu", "0002_alter_linksmode_links_alter_linksmode_texts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sublinksmode",
            name="links_id",
            field=models.ForeignKey(
                db_column="links_id",
                help_text="\n            Пункт меню (ссылка) в который будет\n             опубликован в меню\n            ",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="linksmenu",
                to="module_menu.linksmode",
                verbose_name="Выбрать пункт для меню",
            ),
        ),
    ]
