# Generated by Django 4.2.14 on 2024-10-06 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("module_menu", "0004_alter_menunamesmode_pages_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menunamesmode",
            name="pages_id",
        ),
    ]
