# Generated by Django 4.2.14 on 2024-10-06 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_menu", "0005_remove_menunamesmode_pages_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagemodel",
            name="menu_id",
            field=models.ForeignKey(
                blank=True,
                help_text="\n            Страница на которой будет опубликовано меню\n            ",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pageыmenu",
                to="module_menu.menunamesmode",
                verbose_name="Выбрать меню",
            ),
        ),
    ]
