# Generated by Django 4.2.14 on 2024-10-05 23:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_menu", "0005_alter_linksmode_texts_alter_sublinksmode_texts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linksmode",
            name="texts",
            field=models.CharField(
                blank=True,
                help_text="Текст ссылки (Text refer)",
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        limit_value=50, message="Максимальная длина 50 символов"
                    ),
                    django.core.validators.RegexValidator(
                        message="\n                    Название не должно иметь двух пробелов подряд,\n                    символов не принадлежащих к алфавиту и(или) цифрам.\n                    Начинается из любой буквы. Заканчивается из любой буквы\n                    и(или) цифры.\n                    Допускается дефис и(или) нижнее подчёркивание.\n                    \n                    ",
                        regex="^(?!.*  )[a-zA-Zа-яА-ЯёЁ][\\w \\-_\\dа-яА-ЯёЁ]{1,48}[a-zA-Zа-яА-ЯёЁ]$[^\\S\\W \\\\]?",
                    ),
                ],
                verbose_name="Текст ссылки",
            ),
        ),
        migrations.AlterField(
            model_name="sublinksmode",
            name="texts",
            field=models.CharField(
                blank=True,
                help_text="Текст ссылки (Text refer)",
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        limit_value=50, message="Максимальная длина 50 символов"
                    ),
                    django.core.validators.RegexValidator(
                        message="\n                    Название не должно иметь двух пробелов подряд,\n                    символов не принадлежащих к алфавиту и(или) цифрам.\n                    Начинается из любой буквы. Заканчивается из любой буквы\n                    и(или) цифры.\n                    Допускается дефис и(или) нижнее подчёркивание.\n                    \n                    ",
                        regex="^(?!.*  )[a-zA-Zа-яА-ЯёЁ][\\w \\-_\\dа-яА-ЯёЁ]{1,48}[a-zA-Zа-яА-ЯёЁ]$[^\\S\\W \\\\]?",
                    ),
                ],
                verbose_name="Текст ссылки",
            ),
        ),
    ]
