# Generated by Django 4.2.14 on 2024-10-06 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_menu", "0006_pagemodel_menu_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pagemodel",
            name="menu_id",
        ),
        migrations.AddField(
            model_name="pagemodel",
            name="menu_id",
            field=models.ManyToManyField(
                blank=True,
                help_text="\n            Страница на которой будет опубликовано меню\n            ",
                null=True,
                related_name="pages_menu",
                to="module_menu.menunamesmode",
                verbose_name="Выбрать меню",
            ),
        ),
    ]
