# Generated by Django 4.2.14 on 2024-10-05 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("module_menu", "0006_alter_linksmode_texts_alter_sublinksmode_texts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sublinksmode",
            name="active",
        ),
    ]
