# Generated by Django 4.2.14 on 2024-10-06 02:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_menu", "0007_remove_pagemodel_menu_id_pagemodel_menu_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linksmode",
            name="links",
            field=models.ForeignKey(
                blank=True,
                help_text="\n            Страница на которой будет опубликовано меню\n            ",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pageыlink",
                to="module_menu.pagemodel",
                verbose_name="Выбрать страницу",
            ),
        ),
        migrations.AlterField(
            model_name="linksmode",
            name="texts",
            field=models.CharField(
                blank=True,
                help_text="Текст ссылки (Text refer)",
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        limit_value=50, message="Максимальная длина 50 символов"
                    ),
                    django.core.validators.RegexValidator(
                        message="\n                    Название не должно иметь двух пробелов подряд,\n                    символов не принадлежащих к алфавиту и(или) цифрам.\n                    Начинается из любой буквы. Заканчивается из любой буквы\n                    и(или) цифры.\n                    Допускается дефис и(или) нижнее подчёркивание.\n\n                    ",
                        regex="^(?!.*  )[a-zA-Zа-яА-ЯёЁ][\\w \\-_\\dа-яА-ЯёЁ]{1,48}[a-zA-Zа-яА-ЯёЁ]$[^\\S\\W \\\\]?",
                    ),
                ],
                verbose_name="Текст ссылки",
            ),
        ),
        migrations.AlterField(
            model_name="pagemodel",
            name="menu_id",
            field=models.ManyToManyField(
                blank=True,
                help_text="\n            Список меню которые будут опубликованы на странице.\n            ",
                null=True,
                related_name="pages_menu",
                to="module_menu.menunamesmode",
                verbose_name="Выбрать меню",
            ),
        ),
        migrations.AlterField(
            model_name="pagemodel",
            name="texts",
            field=models.CharField(
                blank=True,
                help_text="Текст ссылки (Text refer)",
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        limit_value=50, message="Максимальная длина 50 символов"
                    ),
                    django.core.validators.RegexValidator(
                        message="\n                    Название не должно иметь двух пробелов подряд,\n                    символов не принадлежащих к алфавиту и(или) цифрам.\n                    Начинается из любой буквы. Заканчивается из любой буквы\n                    и(или) цифры.\n                    Допускается дефис и(или) нижнее подчёркивание.\n\n                    ",
                        regex="^(?!.*  )[a-zA-Zа-яА-ЯёЁ][\\w \\-_\\dа-яА-ЯёЁ]{1,48}[a-zA-Zа-яА-ЯёЁ]$[^\\S\\W \\\\]?",
                    ),
                ],
                verbose_name="Текст ссылки",
            ),
        ),
        migrations.AlterField(
            model_name="sublinksmode",
            name="texts",
            field=models.CharField(
                blank=True,
                help_text="Текст ссылки (Text refer)",
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        limit_value=50, message="Максимальная длина 50 символов"
                    ),
                    django.core.validators.RegexValidator(
                        message="\n                    Название не должно иметь двух пробелов подряд,\n                    символов не принадлежащих к алфавиту и(или) цифрам.\n                    Начинается из любой буквы. Заканчивается из любой буквы\n                    и(или) цифры.\n                    Допускается дефис и(или) нижнее подчёркивание.\n\n                    ",
                        regex="^(?!.*  )[a-zA-Zа-яА-ЯёЁ][\\w \\-_\\dа-яА-ЯёЁ]{1,48}[a-zA-Zа-яА-ЯёЁ]$[^\\S\\W \\\\]?",
                    ),
                ],
                verbose_name="Текст ссылки",
            ),
        ),
    ]
