# Generated by Django 4.2.14 on 2024-10-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_menu", "0007_remove_sublinksmode_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="linksmode",
            name="active",
            field=models.BooleanField(
                default=False,
                help_text="\n         вложенности Активное или не активное меню на странице сайта\n        ",
                verbose_name="Активное или не активное",
            ),
            preserve_default=False,
        ),
    ]
