# Generated by Django 4.2.14 on 2024-10-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_menu", "0008_alter_linksmode_links_alter_linksmode_texts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagemodel",
            name="active",
            field=models.BooleanField(
                default=False,
                help_text='\n         Страница "True"-публикуется.\n        ',
                verbose_name="Активное",
            ),
        ),
    ]
