# Generated by Django 4.2.14 on 2024-10-05 23:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_menu", "0008_linksmode_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="linksmode",
            name="links",
            field=models.CharField(
                help_text="ваш/маршрут/на/внутреннюю/страницу/сайта/",
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.MaxLengthValidator(
                        limit_value=100, message="Максимальная длина 100 символов"
                    ),
                    django.core.validators.RegexValidator(
                        message="Неверный формат ссылки.",
                        regex="^(?!.*  )[a-z][\\w\\-_\\d]{1,98}\\/$[^\\S\\W \\/]?",
                    ),
                ],
                verbose_name="Маршрут",
            ),
        ),
    ]
