# Generated by Django 4.2.14 on 2024-10-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_menu", "0009_alter_linksmode_links"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sublinksmode",
            options={
                "verbose_name": "Меню и под-меню",
                "verbose_name_plural": "Меню и под-меню",
            },
        ),
        migrations.AlterField(
            model_name="linksmode",
            name="active",
            field=models.BooleanField(
                help_text="\n         вложенности Активное или не активное меню на странице сайта\n        ",
                verbose_name="Активное",
            ),
        ),
    ]
