# Generated by Django 4.2.14 on 2024-10-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_menu", "0011_alter_sublinksmode_name_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagemodel",
            name="menu_id",
            field=models.ManyToManyField(
                help_text="\n            Список меню которые будут опубликованы на странице.\n            ",
                related_name="pages_menu",
                to="module_menu.menunamesmode",
                verbose_name="Выбрать меню",
            ),
        ),
    ]
