# Generated by Django 4.2.14 on 2024-10-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("module_menu", "0013_pagemodel_template"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pagemodel",
            old_name="menu_id",
            new_name="menu_list",
        ),
    ]
