# Generated by Django 4.2.14 on 2024-10-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("module_menu", "0017_alter_pagemodel_template"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagemodel",
            name="template",
            field=models.CharField(
                choices=[
                    ("index.html", "Главная"),
                    ("about/index.html", "О нас"),
                    ("account/index.html", "Аккаунт"),
                    ("profile/index.html", "Профиль"),
                    ("404/index.html", "Страница не найдена"),
                ],
                default="404/index.html",
                help_text="\n            HTML-шаблон для контента страницы.\n            ",
                verbose_name="Выбрать шаблон для страницы",
            ),
        ),
    ]
